import "./globals.css";
import { Inter } from "next/font/google";
import Topbar from "@/components/Topbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Finite Automata",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Topbar />
        {children}
      </body>
    </html>
  );
}
